name: Build postmarketOS
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip git openssl
          git clone https://gitlab.postmarketos.org/postmarketOS/pmbootstrap.git
          sudo ln -s $(pwd)/pmbootstrap/pmbootstrap.py /usr/local/bin/pmbootstrap
      - name: Build postmarketOS
        run: |
          # 克隆 aports
          git clone https://gitlab.postmarketos.org/postmarketOS/pmaports.git /home/runner/pmaports
          
          # 直接使用 --aports 指定路径运行，绕过 init 错误
          python3 pmbootstrap/pmbootstrap.py --aports /home/runner/pmaports install
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: postmarketos-xiaomi-santoni
          path: /home/runner/work/chroot_rootfs_xiaomi-santoni/
